/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Iniciar sesión de reclutador o admin */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear vacante a partir de descripción de texto */
        post: operations["createVacancy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vacancies/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener perfil estructurado y skills de una vacante */
        get: operations["getVacancyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar problemas técnicos filtrados por habilidad y nivel */
        get: operations["listProblems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear sesión de entrevista para un candidato (genera link único) */
        post: operations["createInterview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ejecutar código del candidato en el sandbox */
        post: operations["runCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{id}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener la evaluación y rúbrica defendible de una entrevista */
        get: operations["getEvaluation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{id}/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar entrevistas de una organización para el panel de reclutamiento */
        get: operations["listOrganizationInterviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthToken: {
            access_token: string;
            /** @example bearer */
            token_type: string;
            /** @enum {string} */
            role: "admin" | "recruiter";
            organization_id: string;
        };
        CreateVacancyRequest: {
            title: string;
            raw_description: string;
        };
        Vacancy: {
            id: string;
            title: string;
            role_category: string;
            /** @enum {string} */
            seniority: "junior" | "mid" | "senior" | "lead";
            profile?: components["schemas"]["VacancyProfile"];
            /** Format: date-time */
            created_at: string;
        };
        VacancyProfile: {
            required_skills: string[];
            preferred_skills: string[];
            primary_language: string;
            focus_areas?: string[];
        };
        ProblemSummary: {
            id: string;
            title: string;
            /** @enum {string} */
            difficulty: "junior" | "mid" | "senior";
            language: string;
            scenario_preview: string;
            tags?: string[];
        };
        CreateInterviewRequest: {
            vacancy_id: string;
            /** Format: email */
            candidate_email: string;
            candidate_name: string;
        };
        InterviewSession: {
            id: string;
            access_url: string;
            access_token: string;
            /** @enum {string} */
            status: "pending" | "in_progress" | "completed" | "evaluated";
            /** Format: date-time */
            expires_at: string;
        };
        RunCodeRequest: {
            code: string;
            /** @enum {string} */
            language: "python" | "javascript" | "sql";
        };
        RunCodeResponse: {
            /** @enum {string} */
            status: "success" | "test_failure" | "compile_error" | "timeout";
            stdout?: string;
            stderr?: string;
            execution_time_ms?: number;
            tests_passed: number;
            total_tests: number;
            details?: {
                test_name?: string;
                passed?: boolean;
                message?: string;
            }[];
        };
        EvaluationReport: {
            id: string;
            overall_score: number;
            /** @enum {string} */
            recommendation: "hire" | "borderline" | "reject";
            needs_human_review: boolean;
            discrepancy_note?: string;
            competencies: {
                [key: string]: number;
            };
            evidence: {
                competency: string;
                score: number;
                evidence_quote: string;
                turn_id: string;
                reasoning?: string;
            }[];
            strengths?: string[];
            risks?: string[];
            suggested_human_questions?: string[];
        };
        InterviewSummary: {
            id: string;
            candidate_masked_id: string;
            vacancy_title: string;
            status: string;
            overall_score?: number;
            recommendation?: string;
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Token JWT generado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
        };
    };
    createVacancy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVacancyRequest"];
            };
        };
        responses: {
            /** @description Vacante creada con perfil extraído */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vacancy"];
                };
            };
        };
    };
    getVacancyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil extraído de la vacante */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VacancyProfile"];
                };
            };
        };
    };
    listProblems: {
        parameters: {
            query?: {
                skill?: string;
                level?: string;
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de problemas técnicos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemSummary"][];
                };
            };
        };
    };
    createInterview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterviewRequest"];
            };
        };
        responses: {
            /** @description Entrevista creada con token y enlace de acceso */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSession"];
                };
            };
        };
    };
    runCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCodeRequest"];
            };
        };
        responses: {
            /** @description Resultado de la ejecución */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunCodeResponse"];
                };
            };
        };
    };
    getEvaluation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evaluación con evidencias y radar de competencias */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationReport"];
                };
            };
        };
    };
    listOrganizationInterviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de entrevistas con estado y puntuaciones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewSummary"][];
                };
            };
        };
    };
}
